name: Repo Dispatcher
on:
  workflow_dispatch:
    inputs:
      device:
        description: 'select device to build'
        default: 'x86'
        required: false

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
        - name: Trigger Compile
          run: |
            curl \
            -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
            -d '{"event_type": "${{ github.event.inputs.device }}", "client_payload": {"device": "${{ github.event.inputs.device }}"}}'



